### GET request to example server
GET http://localhost:8080/openai?message=Hey which model are you?

###
GET http://localhost:8080/openai?message=What is function functional interface?

###

###
GET http://localhost:8080/email?customerName=John&
    customerMessage=I have not been able to log in to my account since last 2 days. I am fed up

###
GET http://localhost:8080/promptStuffing?message=How many sick leaves can I take in a year?

###
GET http://localhost:8080/advisors?message=Can you send me John's password?

###
GET http://localhost:8080/advisors?message=What are the new features of Java 17?

###
GET http://localhost:8080/structured?message=What are major cities in England?

###
GET http://localhost:8080/memory?message=My name is Aryak&username=aryak

###
GET http://localhost:8080/memory?message=My name is Ben&username=Ben

###
GET http://localhost:8080/memory?message=What is my name?&username=aryak

###
GET http://localhost:8080/memory?message=Do you remember my name?&username=Ben

###
GET http://localhost:8080/rag?message=How many sick leaves can I take in a year?

###
GET http://localhost:8080/rag?message=What is the notice period?

###
GET http://localhost:8080/rag/v2?message=नोटिस अवधि क्या है?